// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHl-kyCTzUwA78alPuggxLiUyTrsMBFlg',
    appId: '1:61308699237:web:4eac9d58eec564bfa4fc8c',
    messagingSenderId: '61308699237',
    projectId: 'todo-hti-b519d',
    authDomain: 'todo-hti-b519d.firebaseapp.com',
    storageBucket: 'todo-hti-b519d.appspot.com',
    measurementId: 'G-XRVTQ7WNSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOLv2DvPeJkHqWPM8Yy_5bywzPM-Wnwd8',
    appId: '1:61308699237:android:3ffb2d3554d40ff0a4fc8c',
    messagingSenderId: '61308699237',
    projectId: 'todo-hti-b519d',
    storageBucket: 'todo-hti-b519d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHMZ9DTT3NObv2xZB2xl-WcaK-DL0yhOk',
    appId: '1:61308699237:ios:f2fe9c7e300444aca4fc8c',
    messagingSenderId: '61308699237',
    projectId: 'todo-hti-b519d',
    storageBucket: 'todo-hti-b519d.appspot.com',
    iosClientId: '61308699237-s72b0tsl99rf6n66k2nd9gflbrtpv90r.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo2',
  );
}
